version: "3.8"
services:
  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: castle
      PGDATA: /tmp
    ports:
      - 5432:5432/tcp
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username admin --dbname castle"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    ports:
      - 6379:6379/tcp
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
