import { mapFromData } from "./items";

export const spellsData = {
  "spell: aanya's animation": "/Aanya%27s_Animation",
  "spell: aanya's quickening": "/Aanya%27s_Quickening",
  "spell: abolish disease": "/Abolish_Disease",
  "spell: abolish enchantment": "/Abolish_Enchantment",
  "spell: abolish poison": "/Abolish_Poison",
  "spell: abscond": "/Abscond",
  "spell: abundant drink": "/Abundant_Drink",
  "spell: abundant food": "/Abundant_Food",
  "spell: accuracy": "/Accuracy",
  "spell: acid jet": "/Acid_Jet",
  "spell: acumen": "/Acumen",
  "spell: adorning grace": "/Adorning_Grace",
  "spell: adroitness": "/Adroitness",
  "spell: aegis": "/Aegis",
  "spell: aegis of bathezid": "/Aegis_of_Bathezid",
  "spell: aegis of ro": "/Aegis_of_Ro",
  "spell: aegolism": "/Aegolism",
  "spell: affliction": "/Affliction",
  "spell: agility": "/Agility",
  "spell: agilmente's aria of eagles": "/Agilmente%27s_Aria_of_Eagles",
  "spell: alacrity": "/Alacrity",
  "spell: alenia's disenchanting melody": "/Alenia%27s_Disenchanting_Melody",
  "spell: alliance": "/Alliance",
  "spell: allure": "/Allure",
  "spell: allure of death": "/Allure_of_Death",
  "spell: allure of the wild": "/Allure_of_the_Wild",
  "spell: alluring aura": "/Alluring_Aura",
  "spell: alluring whispers": "/Alluring_Whispers",
  "spell: aloe sweat": "/Aloe_Sweat",
  "spell: alter plane: hate": "/Alter_Plane:_Hate",
  "spell: alter plane: sky": "/Alter_Plane:_Sky",
  "spell: anarchy": "/Anarchy",
  "spell: ancient breath": "/Ancient_Breath",
  "spell: angstlich's appalling screech": "/Angstlich%27s_Appalling_Screech",
  "spell: angstlich's assonance": "/Angstlich%27s_Assonance",
  "spell: animate dead": "/Animate_Dead",
  "spell: annul magic": "/Annul_Magic",
  "spell: ant legs": "/Ant_Legs",
  "spell: anthem de arms": "/Anthem_De_Arms",
  "spell: antidote": "/Antidote",
  "spell: arch lich": "/Arch_Lich",
  "spell: arch shielding": "/Arch_Shielding",
  "spell: armor of faith": "/Armor_of_Faith",
  "spell: armor of protection": "/Armor_of_Protection",
  "spell: asphyxiate": "/Asphyxiate",
  "spell: assiduous vision": "/Assiduous_Vision",
  "spell: asystole": "/Asystole",
  "spell: atol's spectral shackles": "/Atol%27s_Spectral_Shackles",
  "spell: atone": "/Atone",
  "spell: augment": "/Augment",
  "spell: augment death": "/Augment_Death",
  "spell: augmentation": "/Augmentation",
  "spell: augmentation of death": "/Augmentation_of_Death",
  "spell: aura of antibody": "/Aura_of_Antibody",
  "spell: aura of battle": "/Aura_of_Battle",
  "spell: aura of black petals": "/Aura_of_Black_Petals",
  "spell: aura of blue petals": "/Aura_of_Blue_Petals",
  "spell: aura of cold": "/Aura_of_Cold",
  "spell: aura of green petals": "/Aura_of_Green_Petals",
  "spell: aura of heat": "/Aura_of_Heat",
  "spell: aura of marr": "/Aura_of_Marr",
  "spell: aura of purity": "/Aura_of_Purity",
  "spell: aura of red petals": "/Aura_of_Red_Petals",
  "spell: aura of white petals": "/Aura_of_White_Petals",
  "spell: avalanche": "/Avalanche",
  "spell: avatar": "/Avatar",
  "spell: avatar power": "/Avatar_Power",
  "spell: bandoleer of luclin": "/Bandoleer_of_Luclin",
  "spell: bane of nife": "/Bane_of_Nife",
  "spell: banish summoned": "/Banish_Summoned",
  "spell: banish undead": "/Banish_Undead",
  "spell: banishment": "/Banishment",
  "spell: banishment of shadows": "/Banishment_of_Shadows",
  "spell: banshee aura": "/Banshee_Aura",
  "spell: barbcoat": "/Barbcoat",
  "spell: barrier of combustion": "/Barrier_of_Combustion",
  "spell: barrier of force": "/Barrier_of_Force",
  "spell: battery vision": "/Battery_Vision",
  "spell: bedlam": "/Bedlam",
  "spell: befriend animal": "/Befriend_Animal",
  "spell: beguile": "/Beguile",
  "spell: beguile animals": "/Beguile_Animals",
  "spell: beguile plants": "/Beguile_Plants",
  "spell: beguile undead": "/Beguile_Undead",
  "spell: bellowing winds": "/Bellowing_Winds",
  "spell: benevolence": "/Benevolence",
  "spell: berserker madness i": "/Berserker_Madness_I",
  "spell: berserker madness ii": "/Berserker_Madness_II",
  "spell: berserker madness iii": "/Berserker_Madness_III",
  "spell: berserker madness iv": "/Berserker_Madness_IV",
  "spell: berserker spirit": "/Berserker_Spirit",
  "spell: berserker strength": "/Berserker_Strength",
  "spell: bind affinity": "/Bind_Affinity",
  "spell: bind sight": "/Bind_Sight",
  "spell: bladecoat": "/Bladecoat",
  "spell: blanket of forgetfulness": "/Blanket_of_Forgetfulness",
  "spell: blast of cold": "/Blast_of_Cold",
  "spell: blast of poison": "/Blast_of_Poison",
  "spell: blaze": "/Blaze",
  "spell: blessing of nature": "/Blessing_of_Nature",
  "spell: blessing of the blackstar": "/Blessing_of_the_Blackstar",
  "spell: blessing of the grove": "/Blessing_of_the_Grove",
  "spell: blessing of the theurgist": "/Blessing_of_the_Theurgist",
  "spell: blinding fear": "/Blinding_Fear",
  "spell: blinding luminance": "/Blinding_Luminance",
  "spell: blinding poison i": "/Blinding_Poison_I",
  "spell: blinding poison ii": "/Blinding_Poison_II",
  "spell: blinding poison iii": "/Blinding_Poison_III",
  "spell: blinding step": "/Blinding_Step",
  "spell: blizzard": "/Blizzard",
  "spell: blizzard blast": "/Blizzard_Blast",
  "spell: blood claw": "/Blood_Claw",
  "spell: bobbing corpse": "/Bobbing_Corpse",
  "spell: boil blood": "/Boil_Blood",
  "spell: boiling blood": "/Boiling_Blood",
  "spell: bolt of flame": "/Bolt_of_Flame",
  "spell: bolt of karana": "/Bolt_of_Karana",
  "spell: boltran's agacerie": "/Boltran%27s_Agacerie",
  "spell: boltran's animation": "/Boltran%27s_Animation",
  "spell: bond of death": "/Bond_of_Death",
  "spell: bonds of force": "/Bonds_of_Force",
  "spell: bonds of tunare": "/Bonds_of_Tunare",
  "spell: bone melt": "/Bone_Melt",
  "spell: bone shatter": "/Bone_Shatter",
  "spell: bone walk": "/Bone_Walk",
  "spell: boneshear": "/Boneshear_(Spell)",
  "spell: boon of immolation": "/Boon_of_Immolation",
  "spell: boon of the clear mind": "/Boon_of_the_Clear_Mind",
  "spell: boon of the garou": "/Boon_of_the_Garou",
  "spell: bramblecoat": "/Bramblecoat",
  "spell: bravery": "/Bravery",
  "spell: breath of karana": "/Breath_of_Karana",
  "spell: breath of ro": "/Breath_of_Ro",
  "spell: breath of the dead": "/Breath_of_the_Dead",
  "spell: breath of the sea": "/Breath_of_the_Sea",
  "spell: breeze": "/Breeze",
  "spell: brilliance": "/Brilliance",
  "spell: bristlebane's bundle": "/Bristlebane%27s_Bundle",
  "spell: brittle haste i": "/Brittle_Haste_I",
  "spell: brittle haste ii": "/Brittle_Haste_II",
  "spell: brittle haste iii": "/Brittle_Haste_III",
  "spell: brittle haste iv": "/Brittle_Haste_IV",
  "spell: brusco's boastful bellow": "/Brusco%27s_Boastful_Bellow",
  "spell: brusco's bombastic bellow": "/Brusco%27s_Bombastic_Bellow",
  "spell: bulwark of faith": "/Bulwark_of_Faith",
  "spell: burn": "/Burn",
  "spell: burning vengeance": "/Burning_Vengeance",
  "spell: burningtouch2": "/BurningTouch2",
  "spell: burnout": "/Burnout",
  "spell: burnout ii": "/Burnout_II",
  "spell: burnout iii": "/Burnout_III",
  "spell: burnout iv": "/Burnout_IV",
  "spell: burrowing scarab": "/Burrowing_Scarab",
  "spell: burst of fire": "/Burst_of_Fire",
  "spell: burst of flame": "/Burst_of_Flame",
  "spell: burst of flametest": "/Burst_of_FlameTest",
  "spell: burst of strength": "/Burst_of_Strength",
  "spell: cackling bones": "/Cackling_Bones",
  "spell: cadeau of flame": "/Cadeau_of_Flame",
  "spell: cajole undead": "/Cajole_Undead",
  "spell: cajoling whispers": "/Cajoling_Whispers",
  "spell: calefaction": "/Calefaction",
  "spell: calimony": "/Calimony",
  "spell: call of bones": "/Call_of_Bones",
  "spell: call of earth": "/Call_of_Earth",
  "spell: call of fire": "/Call_of_Fire",
  "spell: call of flame": "/Call_of_Flame",
  "spell: call of karana": "/Call_of_Karana",
  "spell: call of sky": "/Call_of_Sky",
  "spell: call of sky strike": "/Call_of_Sky_Strike",
  "spell: call of the hero": "/Call_of_the_Hero",
  "spell: call of the predator": "/Call_of_the_Predator",
  "spell: call of the zero": "/Call_of_the_Zero",
  "spell: calm": "/Calm",
  "spell: calm animal": "/Calm_Animal",
  "spell: camouflage": "/Camouflage",
  "spell: can o' whoop ass": "/Can_o%27_Whoop_Ass",
  "spell: cancel magic": "/Cancel_Magic",
  "spell: cannibalize": "/Cannibalize",
  "spell: cannibalize ii": "/Cannibalize_II",
  "spell: cannibalize iii": "/Cannibalize_III",
  "spell: cannibalize iv": "/Cannibalize_IV",
  "spell: cantata of replenishment": "/Cantata_of_Replenishment",
  "spell: cantata of soothing": "/Cantata_of_Soothing",
  "spell: captain nalot's quickening": "/Captain_Nalot%27s_Quickening",
  "spell: careless lightning": "/Careless_Lightning",
  "spell: cascade of hail": "/Cascade_of_Hail",
  "spell: cascading darkness": "/Cascading_Darkness",
  "spell: cassindra's chant of clarity": "/Cassindra%27s_Chant_of_Clarity",
  "spell: cassindra's chorus of clarity": "/Cassindra%27s_Chorus_of_Clarity",
  "spell: cassindra's elegy": "/Cassindra%27s_Elegy",
  "spell: cassindra's insipid ditty": "/Cassindra%27s_Insipid_Ditty",
  "spell: cast force": "/Cast_Force",
  "spell: cast sight": "/Cast_Sight",
  "spell: cavorting bones": "/Cavorting_Bones",
  "spell: cazic gate": "/Cazic_Gate",
  "spell: cazic portal": "/Cazic_Portal",
  "spell: cazic touch": "/Cazic_Touch",
  "spell: celerity": "/Celerity",
  "spell: celestial cleansing": "/Celestial_Cleansing",
  "spell: celestial elixir": "/Celestial_Elixir",
  "spell: celestial healing": "/Celestial_Healing",
  "spell: celestial tranquility": "/Celestial_Tranquility",
  "spell: center": "/Center",
  "spell: cessation of cor": "/Cessation_of_Cor",
  "spell: ceticious cloud": "/Ceticious_Cloud",
  "spell: chant of battle": "/Chant_of_Battle",
  "spell: chaos breath": "/Chaos_Breath",
  "spell: chaos flux": "/Chaos_Flux",
  "spell: chaotic feedback": "/Chaotic_Feedback",
  "spell: char": "/Char",
  "spell: charisma": "/Charisma",
  "spell: charm": "/Charm",
  "spell: charm animals": "/Charm_Animals",
  "spell: chase the moon": "/Chase_the_Moon",
  "spell: chill bones": "/Chill_Bones",
  "spell: chill of unlife": "/Chill_of_Unlife",
  "spell: chill sight": "/Chill_Sight",
  "spell: chilling embrace": "/Chilling_Embrace",
  "spell: chloroblast": "/Chloroblast",
  "spell: chloroplast": "/Chloroplast",
  "spell: choke": "/Choke",
  "spell: chords of dissonance": "/Chords_of_Dissonance",
  "spell: cinda's charismatic carillon": "/Cinda%27s_Charismatic_Carillon",
  "spell: cinder bolt": "/Cinder_Bolt",
  "spell: cinder jolt": "/Cinder_Jolt",
  "spell: circle of butcher": "/Circle_of_Butcher",
  "spell: circle of cobalt scar": "/Circle_of_Cobalt_Scar",
  "spell: circle of commons": "/Circle_of_Commons",
  "spell: circle of feerrott": "/Circle_of_Feerrott",
  "spell: circle of force": "/Circle_of_Force",
  "spell: circle of great divide": "/Circle_of_Great_Divide",
  "spell: circle of iceclad": "/Circle_of_Iceclad",
  "spell: circle of karana": "/Circle_of_Karana",
  "spell: circle of lavastorm": "/Circle_of_Lavastorm",
  "spell: circle of misty": "/Circle_of_Misty",
  "spell: circle of ro": "/Circle_of_Ro",
  "spell: circle of steamfont": "/Circle_of_Steamfont",
  "spell: circle of summer": "/Circle_of_Summer",
  "spell: circle of surefall glade": "/Circle_of_Surefall_Glade",
  "spell: circle of the combines": "/Circle_of_the_Combines",
  "spell: circle of toxxulia": "/Circle_of_Toxxulia",
  "spell: circle of wakening lands": "/Circle_of_Wakening_Lands",
  "spell: circle of winter": "/Circle_of_Winter",
  "spell: clarify mana": "/Clarify_Mana",
  "spell: clarity": "/Clarity",
  "spell: clarity ii": "/Clarity_II",
  "spell: claw of the beast": "/Claw_of_the_Beast",
  "spell: cleanse": "/Cleanse",
  "spell: clinging darkness": "/Clinging_Darkness",
  "spell: clockwork poison": "/Clockwork_Poison",
  "spell: cloud": "/Cloud",
  "spell: cloud of disempowerment": "/Cloud_of_Disempowerment",
  "spell: cloud of fear": "/Cloud_of_Fear",
  "spell: cloud of silence": "/Cloud_of_Silence",
  "spell: cobalt scar gate": "/Cobalt_Scar_Gate",
  "spell: cobalt scar portal": "/Cobalt_Scar_Portal",
  "spell: cog boost": "/Cog_Boost",
  "spell: cohesion": "/Cohesion",
  "spell: coldlight": "/Coldlight",
  "spell: collaboration": "/Collaboration",
  "spell: color flux": "/Color_Flux",
  "spell: color shift": "/Color_Shift",
  "spell: color skew": "/Color_Skew",
  "spell: color slant": "/Color_Slant",
  "spell: column of fire": "/Column_of_Fire",
  "spell: column of frost": "/Column_of_Frost",
  "spell: column of lightning": "/Column_of_Lightning",
  "spell: combine gate": "/Combine_Gate",
  "spell: combine portal": "/Combine_Portal",
  "spell: combust": "/Combust",
  "spell: common gate": "/Common_Gate",
  "spell: common portal": "/Common_Portal",
  "spell: companion spirit": "/Companion_Spirit",
  "spell: complete heal": "/Complete_Heal",
  "spell: complete healing": "/Complete_Healing",
  "song: composition of ervaj": "/Composition_of_Ervaj",
  "spell: concussion": "/Concussion",
  "spell: conflagration": "/Conflagration",
  "spell: conglaciation of bone": "/Conglaciation_of_Bone",
  "spell: conjuration: air": "/Conjuration:_Air",
  "spell: conjuration: earth": "/Conjuration:_Earth",
  "spell: conjuration: fire": "/Conjuration:_Fire",
  "spell: conjuration: water": "/Conjuration:_Water",
  "spell: conjure corpse": "/Conjure_Corpse",
  "spell: contact poison i": "/Contact_Poison_I",
  "spell: contact poison ii": "/Contact_Poison_II",
  "spell: contact poison iii": "/Contact_Poison_III",
  "spell: contact poison iv": "/Contact_Poison_IV",
  "spell: convergence": "/Convergence",
  "spell: convoke shadow": "/Convoke_Shadow",
  "spell: cornucopia": "/Cornucopia",
  "spell: corporeal empathy": "/Corporeal_Empathy",
  "spell: counteract disease": "/Counteract_Disease",
  "spell: counteract poison": "/Counteract_Poison",
  "spell: courage": "/Courage",
  "spell: covetous subversion": "/Covetous_Subversion",
  "spell: creeping crud": "/Creeping_Crud",
  "spell: creeping vision": "/Creeping_Vision",
  "spell: cripple": "/Cripple",
  "spell: crission's pixie strike": "/Crission%27s_Pixie_Strike",
  "spell: crystallize mana": "/Crystallize_Mana",
  "spell: cure blindness": "/Cure_Blindness",
  "spell: cure disease": "/Cure_Disease",
  "spell: cure poison": "/Cure_Poison",
  "spell: curse of the garou": "/Curse_of_the_Garou",
  "spell: curse of the simple mind": "/Curse_of_the_Simple_Mind",
  "spell: curse of the spirits": "/Curse_of_the_Spirits",
  "spell: dagger of symbols": "/Dagger_of_Symbols",
  "spell: damage shield": "/Damage_shield",
  "spell: dance of the blade": "/Dance_of_the_Blade",
  "spell: dance of the fireflies": "/Dance_of_the_Fireflies",
  "spell: daring": "/Daring",
  "spell: dark empathy": "/Dark_Empathy",
  "spell: dark pact": "/Dark_Pact",
  "spell: dawncall": "/Dawncall",
  "spell: dazzle": "/Dazzle",
  "spell: dead man floating": "/Dead_Man_Floating",
  "spell: dead men floating": "/Dead_Men_Floating",
  "spell: deadeye": "/Deadeye",
  "spell: deadly lifetap": "/Deadly_Lifetap",
  "spell: deadly poison": "/Deadly_Poison",
  "spell: deadly velium poison": "/Deadly_Velium_Poison",
  "spell: death pact": "/Death_Pact",
  "spell: death peace": "/Death_Peace",
  "spell: deflux": "/Deflux",
  "spell: defoliate": "/Defoliate",
  "spell: defoliation": "/Defoliation",
  "spell: deftness": "/Deftness",
  "spell: deliriously nimble": "/Deliriously_Nimble",
  "spell: dementia": "/Dementia",
  "spell: dementing visions": "/Dementing_Visions",
  "spell: demi lich": "/Demi_Lich",
  "spell: denon's bereavement": "/Denon%27s_Bereavement",
  "spell: denon's desperate dirge": "/Denon%27s_Desperate_Dirge",
  "spell: denon's disruptive discord": "/Denon%27s_Disruptive_Discord",
  "spell: denon's dissension": "/Denon%27s_Dissension",
  "spell: desperate hope": "/Desperate_Hope",
  "spell: devouring darkness": "/Devouring_Darkness",
  "spell: dexterity": "/Dexterity",
  "spell: dexterous aura": "/Dexterous_Aura",
  "spell: diamondskin": "/Diamondskin",
  "spell: dictate": "/Dictate",
  "spell: dimensional hole": "/Dimensional_Hole",
  "spell: dimensional pocket": "/Dimensional_Pocket",
  "spell: discordant mind": "/Discordant_Mind",
  "spell: disease": "/Disease",
  "spell: disease cloud": "/Disease_Cloud",
  "spell: diseased cloud": "/Diseased_Cloud",
  "spell: disempower": "/Disempower",
  "spell: disintegrate": "/Disintegrate",
  "spell: dismiss summoned": "/Dismiss_Summoned",
  "spell: dismiss undead": "/Dismiss_Undead",
  "spell: distill mana": "/Distill_Mana",
  "spell: distraction": "/Distraction",
  "spell: divine aura": "/Divine_Aura",
  "spell: divine barrier": "/Divine_Barrier",
  "spell: divine favor": "/Divine_Favor",
  "spell: divine glory": "/Divine_Glory",
  "spell: divine intervention": "/Divine_Intervention",
  "spell: divine light": "/Divine_Light",
  "spell: divine might": "/Divine_Might",
  "spell: divine might effect": "/Divine_Might_Effect",
  "spell: divine purpose": "/Divine_Purpose",
  "spell: divine strength": "/Divine_Strength",
  "spell: divine wrath": "/Divine_Wrath",
  "spell: dizzy i": "/Dizzy_I",
  "spell: dizzy ii": "/Dizzy_II",
  "spell: dizzy iii": "/Dizzy_III",
  "spell: dizzy iv": "/Dizzy_IV",
  "spell: dizzying wind": "/Dizzying_Wind",
  "spell: doljon's rage": "/Doljon%27s_Rage",
  "spell: dominate undead": "/Dominate_Undead",
  "spell: dooming darkness": "/Dooming_Darkness",
  "spell: draconic rage": "/Draconic_Rage",
  "spell: dragon charm": "/Dragon_Charm",
  "spell: dragon roar": "/Dragon_Roar",
  "spell: drain soul": "/Drain_Soul",
  "spell: drain spirit": "/Drain_Spirit",
  "spell: draught of fire": "/Draught_of_Fire",
  "spell: draught of ice": "/Draught_of_Ice",
  "spell: draught of jiva": "/Draught_of_Jiva",
  "spell: dread of night": "/Dread_of_Night",
  "spell: drifting death": "/Drifting_Death",
  "spell: drones of doom": "/Drones_of_Doom",
  "spell: drowsy": "/Drowsy",
  "spell: dulsehound": "/Dulsehound",
  "spell: dyn's dizzying draught": "/Dyn%27s_Dizzying_Draught",
  "spell: dyzil's deafening decoy": "/Dyzil%27s_Deafening_Decoy",
  "spell: earthcall": "/Earthcall",
  "spell: earthquake": "/Earthquake",
  "spell: ebbing strength": "/Ebbing_Strength",
  "spell: echinacea infusion": "/Echinacea_Infusion",
  "spell: effect: flamesong": "/Effect:_Flamesong",
  "spell: efreeti fire": "/Efreeti_Fire",
  "spell: egress": "/Egress",
  "spell: electric blast": "/Electric_Blast",
  "spell: elemental armor": "/Elemental_Armor",
  "spell: elemental maelstrom": "/Elemental_Maelstrom",
  "spell: elemental rhythms": "/Elemental_Rhythms",
  "spell: elemental shield": "/Elemental_Shield",
  "spell: elemental: air": "/Elemental:_Air",
  "spell: elemental: earth": "/Elemental:_Earth",
  "spell: elemental: fire": "/Elemental:_Fire",
  "spell: elemental: water": "/Elemental:_Water",
  "spell: elementaling: air": "/Elementaling:_Air",
  "spell: elementaling: earth": "/Elementaling:_Earth",
  "spell: elementaling: fire": "/Elementaling:_Fire",
  "spell: elementaling: water": "/Elementaling:_Water",
  "spell: elementalkin: air": "/Elementalkin:_Air",
  "spell: elementalkin: earth": "/Elementalkin:_Earth",
  "spell: elementalkin: fire": "/Elementalkin:_Fire",
  "spell: elementalkin: water": "/Elementalkin:_Water",
  "spell: embrace of the kelpmaiden": "/Embrace_of_the_Kelpmaiden",
  "spell: emissary of thule": "/Emissary_of_Thule",
  "spell: enchant brellium": "/Enchant_Brellium",
  "spell: enchant clay": "/Enchant_Clay",
  "spell: enchant mithril": "/Enchant_Mithril",
  "spell: enchant steel": "/Enchant_Steel",
  "spell: enchant: adamantite": "/Enchant:_Adamantite",
  "spell: enchant: electrum": "/Enchant:_Electrum",
  "spell: enchant: gold": "/Enchant:_Gold",
  "spell: enchant: platinum": "/Enchant:_Platinum",
  "spell: enchant: silver": "/Enchant:_Silver",
  "spell: enchant: velium": "/Enchant:_Velium",
  "spell: endure cold": "/Endure_Cold",
  "spell: endure disease": "/Endure_Disease",
  "spell: endure fire": "/Endure_Fire",
  "spell: endure magic": "/Endure_Magic",
  "spell: endure poison": "/Endure_Poison",
  "spell: enduring breath": "/Enduring_Breath",
  "spell: energy sap": "/Energy_Sap",
  "spell: energy storm": "/Energy_Storm",
  "spell: enfeeblement": "/Enfeeblement",
  "spell: enforced reverence": "/Enforced_Reverence",
  "spell: engorging roots": "/Engorging_Roots",
  "spell: engulfing darkness": "/Engulfing_Darkness",
  "spell: engulfing roots": "/Engulfing_Roots",
  "spell: enlightenment": "/Enlightenment",
  "spell: enslave death": "/Enslave_Death",
  "spell: ensnare": "/Ensnare",
  "spell: ensnaring roots": "/Ensnaring_Roots",
  "spell: enstill": "/Enstill",
  "spell: enthrall": "/Enthrall",
  "spell: enticement of flame": "/Enticement_of_Flame",
  "spell: entomb in ice": "/Entomb_in_Ice",
  "spell: entrance": "/Entrance",
  "spell: entrapping roots": "/Entrapping_Roots",
  "spell: enveloping roots": "/Enveloping_Roots",
  "spell: envenomed bolt": "/Envenomed_Bolt",
  "spell: envenomed breath": "/Envenomed_Breath",
  "spell: envenomed heal": "/Envenomed_Heal",
  "spell: essence drain": "/Essence_Drain",
  "spell: essence tap": "/Essence_Tap",
  "spell: evacuate": "/Evacuate",
  "spell: evacuate: fay": "/Evacuate:_Fay",
  "spell: evacuate: nek": "/Evacuate:_Nek",
  "spell: evacuate: north": "/Evacuate:_North",
  "spell: evacuate: ro": "/Evacuate:_Ro",
  "spell: evacuate: west": "/Evacuate:_West",
  "spell: everfount": "/Everfount",
  "spell: everlasting breath": "/Everlasting_Breath",
  "spell: exile summoned": "/Exile_Summoned",
  "spell: exile undead": "/Exile_Undead",
  "spell: expedience": "/Expedience",
  "spell: expel summoned": "/Expel_Summoned",
  "spell: expel undead": "/Expel_Undead",
  "spell: expulse summoned": "/Expulse_Summoned",
  "spell: expulse undead": "/Expulse_Undead",
  "spell: extended regeneration": "/Extended_Regeneration",
  "spell: extinguish fatigue": "/Extinguish_Fatigue",
  "spell: eye of confusion": "/Eye_of_Confusion",
  "spell: eye of tallon": "/Eye_of_Tallon",
  "spell: eye of zomm": "/Eye_of_Zomm",
  "spell: eyes of the cat": "/Eyes_of_the_Cat",
  "spell: fade": "/Fade",
  "spell: fangol's breath": "/Fangol%27s_Breath",
  "spell: fascination": "/Fascination",
  "spell: fatigue drain": "/Fatigue_Drain",
  "spell: fay gate": "/Fay_Gate",
  "spell: fay portal": "/Fay_Portal",
  "spell: fear": "/Fear",
  "spell: feast of blood": "/Feast_of_Blood",
  "spell: feckless might": "/Feckless_Might",
  "spell: feeble mind i": "/Feeble_Mind_I",
  "spell: feeble mind ii": "/Feeble_Mind_II",
  "spell: feeble mind iii": "/Feeble_Mind_III",
  "spell: feeble mind iv": "/Feeble_Mind_IV",
  "spell: feeble poison": "/Feeble_Poison",
  "spell: feedback": "/Feedback",
  "spell: feet like cat": "/Feet_like_Cat",
  "spell: feign death": "/Feign_Death",
  "spell: fellspine": "/Fellspine_(spell)",
  "spell: feral spirit": "/Feral_Spirit",
  "spell: fetter": "/Fetter",
  "spell: field of bone port": "/Field_of_Bone_Port",
  "spell: fiery death": "/Fiery_Death",
  "spell: fiery might": "/Fiery_Might",
  "spell: fingers of fire": "/Fingers_of_Fire",
  "spell: fire": "/Fire",
  "spell: fire bolt": "/Fire_Bolt",
  "spell: fire flux": "/Fire_Flux",
  "spell: fire spiral of al'kabor": "/Fire_Spiral_of_Al%27Kabor",
  "spell: firefist": "/Firefist",
  "spell: firestorm": "/Firestorm",
  "spell: firestrike": "/Firestrike",
  "spell: fist of air": "/Fist_of_Air",
  "spell: fist of fire": "/Fist_of_Fire",
  "spell: fist of karana": "/Fist_of_Karana",
  "spell: fist of mastery": "/Fist_of_Mastery",
  "spell: fist of sentience": "/Fist_of_Sentience",
  "spell: fist of water": "/Fist_of_Water",
  "spell: fixation of ro": "/Fixation_of_Ro",
  "spell: flame arc": "/Flame_Arc",
  "spell: flame bolt": "/Flame_Bolt",
  "spell: flame flux": "/Flame_Flux",
  "spell: flame lick": "/Flame_Lick",
  "spell: flame of light": "/Flame_of_Light",
  "spell: flame of the efreeti": "/Flame_of_the_Efreeti",
  "spell: flame shock": "/Flame_Shock",
  "spell: flame song of ro": "/Flame_Song_of_Ro",
  "spell: flames of ro": "/Flames_of_Ro",
  "spell: flaming sword of xuzl": "/Flaming_Sword_of_Xuzl",
  "spell: flare": "/Flare",
  "spell: flash of light": "/Flash_of_Light",
  "spell: fleeting fury": "/Fleeting_Fury",
  "spell: flesh rot i": "/Flesh_Rot_I",
  "spell: flesh rot ii": "/Flesh_Rot_II",
  "spell: flesh rot iii": "/Flesh_Rot_III",
  "spell: flowing thought i": "/Flowing_Thought_I",
  "spell: flowing thought ii": "/Flowing_Thought_II",
  "spell: flowing thought iii": "/Flowing_Thought_III",
  "spell: flowing thought v": "/Flowing_Thought_V",
  "spell: flurry": "/Flurry",
  "spell: focus of spirit": "/Focus_of_Spirit",
  "spell: force": "/Force",
  "spell: force shock": "/Force_Shock",
  "spell: force spiral of al'kabor": "/Force_Spiral_of_Al%27Kabor",
  "spell: force strike": "/Force_Strike",
  "spell: forlorn deeds": "/Forlorn_Deeds",
  "spell: form of the great bear": "/Form_of_the_Great_Bear",
  "spell: form of the great wolf": "/Form_of_the_Great_Wolf",
  "spell: form of the howler": "/Form_of_the_Howler",
  "spell: form of the hunter": "/Form_of_the_Hunter",
  "spell: fortitude": "/Fortitude",
  "spell: freezing breath": "/Freezing_Breath",
  "spell: frenzied spirit": "/Frenzied_Spirit",
  "spell: frenzied strength": "/Frenzied_Strength",
  "spell: frenzy": "/Frenzy",
  "spell: froglok poison": "/Froglok_Poison",
  "spell: frost": "/Frost",
  "spell: frost bolt": "/Frost_Bolt",
  "spell: frost breath": "/Frost_Breath",
  "spell: frost port": "/Frost_Port",
  "spell: frost rift": "/Frost_Rift",
  "spell: frost shards": "/Frost_Shards",
  "spell: frost shock": "/Frost_Shock",
  "spell: frost spiral of al'kabor": "/Frost_Spiral_of_Al%27Kabor",
  "spell: frost storm": "/Frost_Storm",
  "spell: frost strike": "/Frost_Strike",
  "spell: frostbite": "/Frostbite_(Spell)",
  "spell: frostreaver's blessing": "/Frostreaver%27s_Blessing",
  "spell: frosty death": "/Frosty_Death",
  "spell: frosty death2": "/Frosty_Death2",
  "spell: fufil's curtailing chant": "/Fufil%27s_Curtailing_Chant",
  "spell: fungal regrowth": "/Fungal_Regrowth",
  "spell: furious strength": "/Furious_Strength",
  "spell: furor": "/Furor",
  "spell: fury": "/Fury",
  "spell: fury of air": "/Fury_of_Air",
  "spell: gale of poison": "/Gale_of_Poison",
  "spell: garzicor's vengeance": "/Garzicor%27s_Vengeance",
  "spell: gasping embrace": "/Gasping_Embrace",
  "spell: gate": "/Gate",
  "spell: gather shadows": "/Gather_Shadows",
  "spell: gaze": "/Gaze",
  "spell: gelatroot": "/GelatRoot",
  "spell: ghoul root": "/Ghoul_Root",
  "spell: gift of aerr": "/Gift_of_Aerr",
  "spell: gift of brilliance": "/Gift_of_Brilliance",
  "spell: gift of insight": "/Gift_of_Insight",
  "spell: gift of magic": "/Gift_of_Magic",
  "spell: gift of pure thought": "/Gift_of_Pure_Thought",
  "spell: gift of xev": "/Gift_of_Xev",
  "spell: girdle of karana": "/Girdle_of_Karana",
  "spell: glamour": "/Glamour",
  "spell: glamour of kintaz": "/Glamour_of_Kintaz",
  "spell: glamour of tunare": "/Glamour_of_Tunare",
  "spell: glimpse": "/Glimpse",
  "spell: grasping roots": "/Grasping_Roots",
  "spell: graveyard dust": "/Graveyard_Dust",
  "spell: gravity flux": "/Gravity_Flux",
  "spell: grease injection": "/Grease_Injection",
  "spell: great divide gate": "/Great_Divide_Gate",
  "spell: great divide portal": "/Great_Divide_Portal",
  "spell: greater conjuration: air": "/Greater_Conjuration:_Air",
  "spell: greater conjuration: earth": "/Greater_Conjuration:_Earth",
  "spell: greater conjuration: fire": "/Greater_Conjuration:_Fire",
  "spell: greater conjuration: water": "/Greater_Conjuration:_Water",
  "spell: greater healing": "/Greater_Healing",
  "spell: greater shielding": "/Greater_Shielding",
  "spell: greater summoning: air": "/Greater_Summoning:_Air",
  "spell: greater summoning: earth": "/Greater_Summoning:_Earth",
  "spell: greater summoning: fire": "/Greater_Summoning:_Fire",
  "spell: greater summoning: water": "/Greater_Summoning:_Water",
  "spell: greater vocaration: air": "/Greater_Vocaration:_Air",
  "spell: greater vocaration: earth": "/Greater_Vocaration:_Earth",
  "spell: greater vocaration: fire": "/Greater_Vocaration:_Fire",
  "spell: greater vocaration: water": "/Greater_Vocaration:_Water",
  "spell: greater wolf form": "/Greater_Wolf_Form",
  "spell: greenmist": "/Greenmist_(Spell)",
  "spell: grim aura": "/Grim_Aura",
  "spell: group resist magic": "/Group_Resist_Magic",
  "spell: guard": "/Guard",
  "spell: guardian": "/Guardian",
  "spell: guardian rhythms": "/Guardian_Rhythms",
  "spell: guardian spirit": "/Guardian_Spirit",
  "spell: halo of light": "/Halo_of_Light",
  "spell: hammer of requital": "/Hammer_of_Requital",
  "spell: hammer of striking": "/Hammer_of_Striking",
  "spell: hammer of wrath": "/Hammer_of_Wrath",
  "spell: harmony": "/Harmony",
  "spell: harmshield": "/Harmshield",
  "spell: harpy voice": "/Harpy_Voice",
  "spell: harvest": "/Harvest",
  "spell: harvest leaves": "/Harvest_Leaves",
  "spell: haste": "/Haste",
  "spell: haunting corpse": "/Haunting_Corpse",
  "spell: haze": "/Haze",
  "spell: healing": "/Healing",
  "spell: health": "/Health",
  "spell: heart flutter": "/Heart_Flutter",
  "spell: heat blood": "/Heat_Blood",
  "spell: heat sight": "/Heat_Sight",
  "spell: heroic bond": "/Heroic_Bond",
  "spell: heroism": "/Heroism",
  "spell: holy armor": "/Holy_Armor",
  "spell: holy might": "/Holy_Might",
  "spell: holy shock": "/Holy_Shock",
  "spell: hsagra's wrath": "/Hsagra%27s_Wrath",
  "spell: hug": "/Hug",
  "spell: hungry earth": "/Hungry_Earth",
  "spell: hymn of restoration": "/Hymn_of_Restoration",
  "spell: ice": "/Ice",
  "spell: ice breath": "/Ice_Breath",
  "spell: ice comet": "/Ice_Comet",
  "spell: ice rend": "/Ice_Rend",
  "spell: ice shock": "/Ice_Shock",
  "spell: ice spear of solist": "/Ice_Spear_of_Solist",
  "spell: ice strike": "/Ice_Strike",
  "spell: iceclad gate": "/Iceclad_Gate",
  "spell: iceclad portal": "/Iceclad_Portal",
  "spell: icestrike": "/Icestrike",
  "spell: identify": "/Identify",
  "spell: ignite": "/Ignite",
  "spell: ignite blood": "/Ignite_Blood",
  "spell: ignite bones": "/Ignite_Bones",
  "spell: ikatiar's revenge": "/Ikatiar%27s_Revenge",
  "spell: illusion: air elemental": "/Illusion:_Air_Elemental",
  "spell: illusion: barbarian": "/Illusion:_Barbarian",
  "spell: illusion: dark elf": "/Illusion:_Dark_Elf",
  "spell: illusion: drybone": "/Illusion:_Drybone",
  "spell: illusion: dwarf": "/Illusion:_Dwarf",
  "spell: illusion: earth elemental": "/Illusion:_Earth_Elemental",
  "spell: illusion: erudite": "/Illusion:_Erudite",
  "spell: illusion: fire elemental": "/Illusion:_Fire_Elemental",
  "spell: illusion: gnome": "/Illusion:_Gnome",
  "spell: illusion: half-elf": "/Illusion:_Half-Elf",
  "spell: illusion: halfling": "/Illusion:_Halfling",
  "spell: illusion: high elf": "/Illusion:_High_Elf",
  "spell: illusion: human": "/Illusion:_Human",
  "spell: illusion: iksar": "/Illusion:_Iksar",
  "spell: illusion: ogre": "/Illusion:_Ogre",
  "spell: illusion: skeleton": "/Illusion:_Skeleton",
  "spell: illusion: spirit wolf": "/Illusion:_Spirit_Wolf",
  "spell: illusion: tree": "/Illusion:_Tree",
  "spell: illusion: troll": "/Illusion:_Troll",
  "spell: illusion: water elemental": "/Illusion:_Water_Elemental",
  "spell: illusion: werewolf": "/Illusion:_Werewolf",
  "spell: illusion: wood elf": "/Illusion:_Wood_Elf",
  "spell: imbue amber": "/Imbue_Amber",
  "spell: imbue black pearl": "/Imbue_Black_Pearl",
  "spell: imbue black sapphire": "/Imbue_Black_Sapphire",
  "spell: imbue diamond": "/Imbue_Diamond",
  "spell: imbue emerald": "/Imbue_Emerald",
  "spell: imbue fire opal": "/Imbue_Fire_Opal",
  "spell: imbue ivory": "/Imbue_Ivory",
  "spell: imbue jade": "/Imbue_Jade",
  "spell: imbue opal": "/Imbue_Opal",
  "spell: imbue peridot": "/Imbue_Peridot",
  "spell: imbue plains pebble": "/Imbue_Plains_Pebble",
  "spell: imbue rose quartz": "/Imbue_Rose_Quartz",
  "spell: imbue ruby": "/Imbue_Ruby",
  "spell: imbue sapphire": "/Imbue_Sapphire",
  "spell: imbue topaz": "/Imbue_Topaz",
  "spell: immobilize": "/Immobilize",
  "spell: immolate": "/Immolate",
  "spell: immolating breath": "/Immolating_Breath",
  "spell: impart strength": "/Impart_Strength",
  "spell: improved invis to undead": "/Improved_Invis_to_Undead",
  "spell: improved invisibility": "/Improved_Invisibility",
  "spell: improved superior camouflage": "/Improved_Superior_Camouflage",
  "spell: incapacitate": "/Incapacitate",
  "spell: incinerate bones": "/Incinerate_Bones",
  "spell: infectious cloud": "/Infectious_Cloud",
  "spell: inferno of al'kabor": "/Inferno_of_Al%27Kabor",
  "spell: inferno shield": "/Inferno_Shield",
  "spell: inferno shock": "/Inferno_Shock",
  "spell: infusion": "/Infusion",
  "spell: injected poison i": "/Injected_Poison_I",
  "spell: injected poison ii": "/Injected_Poison_II",
  "spell: injected poison iii": "/Injected_Poison_III",
  "spell: injected poison iv": "/Injected_Poison_IV",
  "spell: injected poison v": "/Injected_Poison_V",
  "spell: inner fire": "/Inner_Fire",
  "spell: insidious decay": "/Insidious_Decay",
  "spell: insidious fever": "/Insidious_Fever",
  "spell: insidious malady": "/Insidious_Malady",
  "spell: insight": "/Insight",
  "spell: insipid weakness": "/Insipid_Weakness",
  "spell: inspire fear": "/Inspire_Fear",
  "spell: intensify death": "/Intensify_Death",
  "spell: invert gravity": "/Invert_Gravity",
  "spell: invigor": "/Invigor",
  "spell: invigorate": "/Invigorate",
  "spell: invisibility": "/Invisibility",
  "spell: invisibility cloak": "/Invisibility_Cloak",
  "spell: invisibility to undead": "/Invisibility_to_Undead",
  "spell: invisibility versus animal": "/Invisibility_versus_Animal",
  "spell: invisibility versus animals": "/Invisibility_versus_Animals",
  "spell: invisibility versus undead": "/Invisibility_versus_Undead",
  "spell: invoke death": "/Invoke_Death",
  "spell: invoke fear": "/Invoke_Fear",
  "spell: invoke lightning": "/Invoke_Lightning",
  "spell: invoke shadow": "/Invoke_Shadow",
  "spell: jaxan's jig o' vigor": "/Jaxan%27s_Jig_o%27_Vigor",
  "spell: jolt": "/Jolt",
  "spell: jonthan's inspiration": "/Jonthan%27s_Inspiration",
  "spell: jonthan's provocation": "/Jonthan%27s_Provocation",
  "spell: jonthan's whistling warsong": "/Jonthan%27s_Whistling_Warsong",
  "spell: journeymanboots": "/JourneymanBoots",
  "spell: judgment of ice": "/Judgment_of_Ice",
  "spell: juli's animation": "/Juli%27s_Animation",
  "spell: jyll's static pulse": "/Jyll%27s_Static_Pulse",
  "spell: jyll's wave of heat": "/Jyll%27s_Wave_of_Heat",
  "spell: jyll's zephyr of ice": "/Jyll%27s_Zephyr_of_Ice",
  "spell: kazumi's note of preservation": "/Kazumi%27s_Note_of_Preservation",
  "spell: kelin's lucid lullaby": "/Kelin%27s_Lucid_Lullaby",
  "spell: kelin's lugubrious lament": "/Kelin%27s_Lugubrious_Lament",
  "spell: kilan's animation": "/Kilan%27s_Animation",
  "spell: kilva's skin of flame": "/Kilva%27s_Skin_of_Flame_(Spell)",
  "spell: kintaz's animation": "/Kintaz%27s_Animation",
  "spell: knight's blessing": "/Knight%27s_Blessing",
  "spell: knockback": "/Knockback",
  "spell: kylie's venom": "/Kylie%27s_Venom",
  "spell: languid pace": "/Languid_Pace",
  "spell: largarn's lamentation": "/Largarn%27s_Lamentation",
  "spell: largo's absonant binding": "/Largo%27s_Absonant_Binding",
  "spell: largo's melodic binding": "/Largo%27s_Melodic_Binding",
  "spell: lava bolt": "/Lava_Bolt",
  "spell: lava breath": "/Lava_Breath",
  "spell: lava storm": "/Lava_Storm",
  "spell: leach": "/Leach",
  "spell: leatherskin": "/Leatherskin",
  "spell: leering corpse": "/Leering_Corpse",
  "spell: legacy of spike": "/Legacy_of_Spike",
  "spell: legacy of thorn": "/Legacy_of_Thorn",
  "spell: lesser conjuration: air": "/Lesser_Conjuration:_Air",
  "spell: lesser conjuration: earth": "/Lesser_Conjuration:_Earth",
  "spell: lesser conjuration: fire": "/Lesser_Conjuration:_Fire",
  "spell: lesser conjuration: water": "/Lesser_Conjuration:_Water",
  "spell: lesser shielding": "/Lesser_Shielding",
  "spell: lesser summoning: air": "/Lesser_Summoning:_Air",
  "spell: lesser summoning: earth": "/Lesser_Summoning:_Earth",
  "spell: lesser summoning: fire": "/Lesser_Summoning:_Fire",
  "spell: lesser summoning: water": "/Lesser_Summoning:_Water",
  "spell: levant": "/Levant",
  "spell: levitate": "/Levitate",
  "spell: levitation": "/Levitation",
  "spell: lich": "/Lich",
  "spell: life leech": "/Life_Leech",
  "spell: lifedraw": "/Lifedraw",
  "spell: lifespike": "/Lifespike",
  "spell: lifetap": "/Lifetap",
  "spell: light healing": "/Light_Healing",
  "spell: lightning blast": "/Lightning_Blast",
  "spell: lightning bolt": "/Lightning_Bolt",
  "spell: lightning breath": "/Lightning_Breath",
  "spell: lightning shock": "/Lightning_Shock",
  "spell: lightning storm": "/Lightning_Storm",
  "spell: lightning strike": "/Lightning_Strike",
  "spell: liquid silver i": "/Liquid_Silver_I",
  "spell: liquid silver ii": "/Liquid_Silver_II",
  "spell: liquid silver iii": "/Liquid_Silver_III",
  "spell: listless power": "/Listless_Power",
  "spell: locate corpse": "/Locate_Corpse",
  "spell: lower element": "/Lower_Element",
  "spell: lower resists i": "/Lower_Resists_I",
  "spell: lower resists ii": "/Lower_Resists_II",
  "spell: lower resists iii": "/Lower_Resists_III",
  "spell: lower resists iv": "/Lower_Resists_IV",
  "spell: lull": "/Lull",
  "spell: lull animal": "/Lull_Animal",
  "spell: lure of flame": "/Lure_of_Flame",
  "spell: lure of frost": "/Lure_of_Frost",
  "spell: lure of ice": "/Lure_of_Ice",
  "spell: lure of lightning": "/Lure_of_Lightning",
  "spell: lyssa's cataloging libretto": "/Lyssa%27s_Cataloging_Libretto",
  "spell: lyssa's locating lyric": "/Lyssa%27s_Locating_Lyric",
  "spell: lyssa's solidarity of vision": "/Lyssa%27s_Solidarity_of_Vision",
  "spell: lyssa's veracious concord": "/Lyssa%27s_Veracious_Concord",
  "spell: magi curse": "/Magi_Curse",
  "spell: magnify": "/Magnify",
  "spell: major shielding": "/Major_Shielding",
  "spell: mala": "/Mala",
  "spell: malaise": "/Malaise",
  "spell: malaisement": "/Malaisement",
  "spell: malevolent grasp": "/Malevolent_Grasp",
  "spell: malignant dead": "/Malignant_Dead",
  "spell: malo": "/Malo",
  "spell: malosi": "/Malosi",
  "spell: malosini": "/Malosini",
  "spell: mana conversion": "/Mana_Conversion",
  "spell: mana convert": "/Mana_Convert",
  "spell: mana flare": "/Mana_Flare",
  "spell: mana shroud": "/Mana_Shroud",
  "spell: mana sieve": "/Mana_Sieve",
  "spell: mana sink": "/Mana_Sink",
  "spell: manasink": "/Manasink",
  "spell: manaskin": "/Manaskin",
  "spell: manastorm": "/Manastorm",
  "spell: maniacal strength": "/Maniacal_Strength",
  "spell: manifest elements": "/Manifest_Elements",
  "spell: manticore poison": "/Manticore_Poison",
  "spell: mark of karn": "/Mark_of_Karn",
  "spell: markar's clash": "/Markar%27s_Clash",
  "spell: markar's discord": "/Markar%27s_Discord",
  "spell: markar's relocation": "/Markar%27s_Relocation",
  "spell: mask of the hunter": "/Mask_of_the_Hunter",
  "spell: mcvaxius' berserker crescendo": "/McVaxius%27_Berserker_Crescendo",
  "spell: mcvaxius' rousing rondo": "/McVaxius%27_Rousing_Rondo",
  "spell: melanie's mellifluous motion": "/Melanie%27s_Mellifluous_Motion",
  "spell: melodious befuddlement": "/Melodious_Befuddlement",
  "spell: melody of ervaj": "/Melody_of_Ervaj",
  "spell: memory blur": "/Memory_Blur",
  "spell: memory flux": "/Memory_Flux",
  "spell: mend bones": "/Mend_Bones",
  "spell: mesmerization": "/Mesmerization",
  "spell: mesmerize": "/Mesmerize",
  "spell: mesmerizing breath": "/Mesmerizing_Breath",
  "spell: mind cloud": "/Mind_Cloud",
  "spell: mind wipe": "/Mind_Wipe",
  "spell: minion of hate": "/Minion_of_Hate",
  "spell: minion of shadows": "/Minion_of_Shadows",
  "spell: minor conjuration: air": "/Minor_Conjuration:_Air",
  "spell: minor conjuration: earth": "/Minor_Conjuration:_Earth",
  "spell: minor conjuration: fire": "/Minor_Conjuration:_Fire",
  "spell: minor conjuration: water": "/Minor_Conjuration:_Water",
  "spell: minor healing": "/Minor_Healing",
  "spell: minor illusion": "/Minor_Illusion",
  "spell: minor shielding": "/Minor_Shielding",
  "spell: minor summoning: air": "/Minor_Summoning:_Air",
  "spell: minor summoning: earth": "/Minor_Summoning:_Earth",
  "spell: minor summoning: fire": "/Minor_Summoning:_Fire",
  "spell: minor summoning: water": "/Minor_Summoning:_Water",
  "spell: mircyl's animation": "/Mircyl%27s_Animation",
  "spell: mist": "/Mist",
  "spell: mistwalker": "/Mistwalker",
  "spell: modulating rod": "/Modulating_Rod",
  "spell: modulation": "/Modulation",
  "spell: monster summoning i": "/Monster_Summoning_I",
  "spell: monster summoning ii": "/Monster_Summoning_II",
  "spell: monster summoning iii": "/Monster_Summoning_III",
  "spell: mortal deftness": "/Mortal_Deftness",
  "spell: muscle lock i": "/Muscle_Lock_I",
  "spell: muscle lock ii": "/Muscle_Lock_II",
  "spell: muscle lock iii": "/Muscle_Lock_III",
  "spell: muscle lock iv": "/Muscle_Lock_IV",
  "spell: muzzle of mardu": "/Muzzle_of_Mardu",
  "spell: mystic precision": "/Mystic_Precision",
  "spell: naltron's mark": "/Naltron%27s_Mark",
  "spell: nature walkers behest": "/Nature_Walkers_Behest",
  "spell: nature's holy wrath": "/Nature%27s_Holy_Wrath",
  "spell: nature's touch": "/Nature%27s_Touch",
  "spell: nature's wrath": "/Nature%27s_Wrath_(Spell)",
  "spell: natureskin": "/Natureskin",
  "spell: nek gate": "/Nek_Gate",
  "spell: nek portal": "/Nek_Portal",
  "spell: neutralize magic": "/Neutralize_Magic",
  "spell: nillipus' march of the wee": "/Nillipus%27_March_of_the_Wee",
  "spell: nimble": "/Nimble",
  "spell: niv's harmonic": "/Niv%27s_Harmonic",
  "spell: niv's melody of preservation": "/Niv%27s_Melody_of_Preservation",
  "spell: north gate": "/North_Gate",
  "spell: north portal": "/North_Portal",
  "spell: null aura": "/Null_Aura",
  "spell: nullify magic": "/Nullify_Magic",
  "spell: numb the dead": "/Numb_the_Dead",
  "spell: numbing cold": "/Numbing_Cold",
  "spell: o'keils flickering flame": "/O%27Keils_Flickering_Flame",
  "spell: o'keils radiation": "/O%27Keils_Radiation",
  "spell: obscure": "/Obscure",
  "spell: obsidian shatter": "/Obsidian_Shatter",
  "song: occlusion of sound": "/Occlusion_of_Sound",
  "spell: one hundred blows": "/One_Hundred_Blows",
  "spell: overthere": "/Overthere_(Spell)",
  "spell: overwhelming splendor": "/Overwhelming_Splendor",
  "spell: pacify": "/Pacify",
  "spell: pack chloroplast": "/Pack_Chloroplast",
  "spell: pack regeneration": "/Pack_Regeneration",
  "spell: pack spirit": "/Pack_Spirit",
  "spell: pact of shadow": "/Pact_of_Shadow",
  "spell: panic": "/Panic",
  "spell: panic animal": "/Panic_Animal",
  "spell: panic the dead": "/Panic_the_Dead",
  "spell: paralyzing earth": "/Paralyzing_Earth",
  "spell: paralyzing poison i": "/Paralyzing_Poison_I",
  "spell: paralyzing poison ii": "/Paralyzing_Poison_II",
  "spell: paralyzing poison iii": "/Paralyzing_Poison_III",
  "spell: pendril's animation": "/Pendril%27s_Animation",
  "spell: phantom armor": "/Phantom_Armor",
  "spell: phantom chain": "/Phantom_Chain",
  "spell: phantom leather": "/Phantom_Leather",
  "spell: phantom plate": "/Phantom_Plate",
  "spell: phobocancel": "/Phobocancel",
  "spell: pillage enchantment": "/Pillage_Enchantment",
  "spell: pillar of fire": "/Pillar_of_Fire",
  "spell: pillar of flame": "/Pillar_of_Flame",
  "spell: pillar of frost": "/Pillar_of_Frost",
  "spell: pillar of lightning": "/Pillar_of_Lightning",
  "spell: plague": "/Plague",
  "spell: plagueratdisease": "/PlagueRatDisease",
  "spell: plainsight": "/Plainsight",
  "spell: pogonip": "/Pogonip",
  "spell: poison": "/Poison",
  "spell: poison animal i": "/Poison_Animal_I",
  "spell: poison animal ii": "/Poison_Animal_II",
  "spell: poison animal iii": "/Poison_Animal_III",
  "spell: poison bolt": "/Poison_Bolt",
  "spell: poison breath": "/Poison_Breath",
  "spell: poison storm": "/Poison_Storm",
  "spell: poison summoned i": "/Poison_Summoned_I",
  "spell: poison summoned ii": "/Poison_Summoned_II",
  "spell: poison summoned iii": "/Poison_Summoned_III",
  "spell: poisonous chill": "/Poisonous_Chill",
  "spell: porlos' fury": "/Porlos%27_Fury",
  "spell: pouch of quellious": "/Pouch_of_Quellious",
  "spell: power": "/Power",
  "spell: power of the forests": "/Power_of_the_Forests",
  "spell: pox of bertoxxulous": "/Pox_of_Bertoxxulous",
  "spell: primal avatar": "/Primal_Avatar",
  "spell: primal essence": "/Primal_Essence",
  "spell: prime healers blessing": "/Prime_Healers_Blessing",
  "spell: produce wrench": "/Produce_Wrench",
  "spell: project lightning": "/Project_Lightning",
  "spell: protect": "/Protect",
  "spell: protection of the glades": "/Protection_of_the_Glades",
  "spell: psalm of cooling": "/Psalm_of_Cooling",
  "spell: psalm of mystic shielding": "/Psalm_of_Mystic_Shielding",
  "spell: psalm of purity": "/Psalm_of_Purity",
  "spell: psalm of vitality": "/Psalm_of_Vitality",
  "spell: psalm of warmth": "/Psalm_of_Warmth",
  "spell: purge": "/Purge",
  "spell: purify mana": "/Purify_Mana",
  "spell: purifying rhythms": "/Purifying_Rhythms",
  "spell: putrefy flesh": "/Putrefy_Flesh",
  "spell: putrid breath": "/Putrid_Breath",
  "spell: pyrocruor": "/Pyrocruor",
  "spell: quickness": "/Quickness",
  "spell: quiver of marr": "/Quiver_of_Marr",
  "spell: quivering veil of xarn": "/Quivering_Veil_of_Xarn",
  "spell: rabies": "/Rabies",
  "spell: radiant visage": "/Radiant_Visage",
  "spell: rage": "/Rage",
  "spell: rage of tallon": "/Rage_of_Tallon",
  "spell: rage of the sky": "/Rage_of_the_Sky",
  "spell: rage of vallon": "/Rage_of_Vallon",
  "spell: rage of zek": "/Rage_of_Zek",
  "spell: rage of zomm": "/Rage_of_Zomm",
  "spell: raging strength": "/Raging_Strength",
  "spell: rain of blades": "/Rain_of_Blades",
  "spell: rain of fire": "/Rain_of_Fire",
  "spell: rain of lava": "/Rain_of_Lava",
  "spell: rain of molten lava": "/Rain_of_Molten_Lava",
  "spell: rain of spikes": "/Rain_of_Spikes",
  "spell: rain of swords": "/Rain_of_Swords",
  "spell: rampage": "/Rampage",
  "spell: rapacious subversion": "/Rapacious_Subversion",
  "spell: rapture": "/Rapture",
  "spell: recant magic": "/Recant_Magic",
  "spell: reckless health": "/Reckless_Health",
  "spell: reckless strength": "/Reckless_Strength",
  "spell: reckoning": "/Reckoning",
  "spell: reclaim energy": "/Reclaim_Energy",
  "spell: regeneration": "/Regeneration",
  "spell: regrowth": "/Regrowth",
  "spell: regrowth of the grove": "/Regrowth_of_the_Grove",
  "spell: rejuvenation": "/Rejuvenation",
  "spell: remedy": "/Remedy",
  "spell: rend": "/Rend",
  "spell: renew bones": "/Renew_Bones",
  "spell: renew elements": "/Renew_Elements",
  "spell: renew summoning": "/Renew_Summoning",
  "spell: reoccurring amnesia": "/Reoccurring_Amnesia",
  "spell: repulse animal": "/Repulse_Animal",
  "spell: resist cold": "/Resist_Cold",
  "spell: resist disease": "/Resist_Disease",
  "spell: resist fire": "/Resist_Fire",
  "spell: resist magic": "/Resist_Magic",
  "spell: resist poison": "/Resist_Poison",
  "spell: resistant skin": "/Resistant_Skin",
  "spell: resolution": "/Resolution",
  "spell: rest the dead": "/Rest_the_Dead",
  "spell: restless bones": "/Restless_Bones",
  "spell: restore sight": "/Restore_Sight",
  "spell: resurrection": "/Resurrection",
  "spell: resurrection effects": "/Resurrection_Effects",
  "spell: resuscitate": "/Resuscitate",
  "spell: retribution": "/Retribution",
  "spell: retribution of al`kabor": "/Retribution_of_Al%27Kabor",
  "spell: revive": "/Revive",
  "spell: reviviscence": "/Reviviscence",
  "spell: ring of butcher": "/Ring_of_Butcher",
  "spell: ring of cobalt scar": "/Ring_of_Cobalt_Scar",
  "spell: ring of commons": "/Ring_of_Commons",
  "spell: ring of faydark": "/Ring_of_Faydark",
  "spell: ring of feerrott": "/Ring_of_Feerrott",
  "spell: ring of great divide": "/Ring_of_Great_Divide",
  "spell: ring of iceclad": "/Ring_of_Iceclad",
  "spell: ring of karana": "/Ring_of_Karana",
  "spell: ring of lavastorm": "/Ring_of_Lavastorm",
  "spell: ring of misty": "/Ring_of_Misty",
  "spell: ring of ro": "/Ring_of_Ro",
  "spell: ring of steamfont": "/Ring_of_Steamfont",
  "spell: ring of surefall glade": "/Ring_of_Surefall_Glade",
  "spell: ring of the combines": "/Ring_of_the_Combines",
  "spell: ring of toxxulia": "/Ring_of_Toxxulia",
  "spell: ring of wakening lands": "/Ring_of_Wakening_Lands",
  "spell: riotous health": "/Riotous_Health",
  "spell: rising dexterity": "/Rising_Dexterity",
  "spell: ro gate": "/Ro_Gate",
  "spell: ro portal": "/Ro_Portal",
  "spell: ro's fiery sundering": "/Ro%27s_Fiery_Sundering",
  "spell: rodrick's gift": "/Rodrick%27s_Gift",
  "spell: root": "/Root",
  "spell: rotting flesh": "/Rotting_Flesh",
  "spell: rubicite aura": "/Rubicite_Aura",
  "spell: rune i": "/Rune_I",
  "spell: rune ii": "/Rune_II",
  "spell: rune iii": "/Rune_III",
  "spell: rune iv": "/Rune_IV",
  "spell: rune v": "/Rune_V",
  "spell: sacrifice": "/Sacrifice_(spell)",
  "spell: sagar's animation": "/Sagar%27s_Animation",
  "spell: sanity warp": "/Sanity_Warp",
  "spell: sathir's mesmerization": "/Sathir%27s_Mesmerization",
  "spell: savage spirit": "/Savage_Spirit",
  "spell: scale of wolf": "/Scale_of_Wolf",
  "spell: scale skin": "/Scale_Skin",
  "spell: scarab storm": "/Scarab_Storm",
  "spell: scars of sigil": "/Scars_of_Sigil",
  "spell: scent of darkness": "/Scent_of_Darkness",
  "spell: scent of dusk": "/Scent_of_Dusk",
  "spell: scent of shadow": "/Scent_of_Shadow",
  "spell: scent of terris": "/Scent_of_Terris",
  "spell: scintillation": "/Scintillation",
  "spell: scorching skin": "/Scorching_Skin",
  "spell: scoriae": "/Scoriae",
  "spell: scourge": "/Scourge",
  "spell: scream of chaos": "/Scream_of_Chaos",
  "spell: screaming mace": "/Screaming_Mace_(Spell)",
  "spell: screaming terror": "/Screaming_Terror",
  "spell: sear": "/Sear",
  "spell: sebilite pox": "/Sebilite_Pox",
  "spell: sedulous subversion": "/Sedulous_Subversion",
  "spell: see invisible": "/See_Invisible",
  "spell: seeking flame of seukor": "/Seeking_Flame_of_Seukor",
  "spell: seething fury": "/Seething_Fury",
  "spell: selo's accelerando": "/Selo%27s_Accelerando",
  "spell: selo's assonant strane": "/Selo%27s_Assonant_Strane",
  "spell: selo's chords of cessation": "/Selo%27s_Chords_of_Cessation",
  "spell: selo's consonant chain": "/Selo%27s_Consonant_Chain",
  "spell: selo's song of travel": "/Selo%27s_Song_of_Travel",
  "spell: sense animals": "/Sense_Animals",
  "spell: sense summoned": "/Sense_Summoned",
  "spell: sense the dead": "/Sense_the_Dead",
  "spell: sentinel": "/Sentinel",
  "spell: serpent sight": "/Serpent_Sight",
  "spell: servant of bones": "/Servant_of_Bones",
  "spell: shade": "/Shade",
  "spell: shadow": "/Shadow",
  "spell: shadow compact": "/Shadow_Compact",
  "spell: shadow sight": "/Shadow_Sight",
  "spell: shadow step": "/Shadow_Step",
  "spell: shadow vortex": "/Shadow_Vortex",
  "spell: shadowbond": "/Shadowbond",
  "spell: shalee's animation": "/Shalee%27s_Animation",
  "spell: shallow breath": "/Shallow_Breath",
  "spell: shards of sorrow": "/Shards_of_Sorrow",
  "spell: share wolf form": "/Share_Wolf_Form",
  "spell: shauri's sonorous clouding": "/Shauri%27s_Sonorous_Clouding",
  "spell: shield of barbs": "/Shield_of_Barbs",
  "spell: shield of blades": "/Shield_of_Blades",
  "spell: shield of brambles": "/Shield_of_Brambles",
  "spell: shield of fire": "/Shield_of_Fire",
  "spell: shield of flame": "/Shield_of_Flame",
  "spell: shield of lava": "/Shield_of_Lava",
  "spell: shield of song": "/Shield_of_Song",
  "spell: shield of spikes": "/Shield_of_Spikes",
  "spell: shield of the eighth": "/Shield_of_the_Eighth",
  "spell: shield of the magi": "/Shield_of_the_Magi",
  "spell: shield of thistles": "/Shield_of_Thistles",
  "spell: shield of thorns": "/Shield_of_Thorns_(Spell)",
  "spell: shield of words": "/Shield_of_Words",
  "spell: shielding": "/Shielding",
  "spell: shieldskin": "/Shieldskin",
  "spell: shifting shield": "/Shifting_Shield",
  "spell: shifting sight": "/Shifting_Sight",
  "spell: shiftless deeds": "/Shiftless_Deeds",
  "spell: shock of blades": "/Shock_of_Blades",
  "spell: shock of fire": "/Shock_of_Fire",
  "spell: shock of flame": "/Shock_of_Flame",
  "spell: shock of frost": "/Shock_of_Frost",
  "spell: shock of ice": "/Shock_of_Ice",
  "spell: shock of lightning": "/Shock_of_Lightning",
  "spell: shock of poison": "/Shock_of_Poison",
  "spell: shock of spikes": "/Shock_of_Spikes",
  "spell: shock of steel": "/Shock_of_Steel",
  "spell: shock of swords": "/Shock_of_Swords",
  "spell: shock of the tainted": "/Shock_of_the_Tainted",
  "spell: shock spiral of al'kabor": "/Shock_Spiral_of_Al%27Kabor",
  "spell: shrieking howl": "/Shrieking_Howl",
  "spell: shrink": "/Shrink",
  "spell: shroud of death": "/Shroud_of_Death",
  "spell: shroud of hate": "/Shroud_of_Hate",
  "spell: shroud of pain": "/Shroud_of_Pain",
  "spell: shroud of the spirits": "/Shroud_of_the_Spirits",
  "spell: shroud of undeath": "/Shroud_of_Undeath",
  "spell: sicken": "/Sicken",
  "spell: sight": "/Sight",
  "spell: sight graft": "/Sight_Graft",
  "spell: silver breath": "/Silver_Breath",
  "spell: silver skin": "/Silver_Skin",
  "spell: siphon": "/Siphon",
  "spell: siphon life": "/Siphon_Life",
  "spell: siphon strength": "/Siphon_Strength",
  "spell: siphon strength recourse": "/Siphon_Strength_Recourse",
  "spell: sirocco": "/Sirocco",
  "spell: sisna's animation": "/Sisna%27s_Animation",
  "spell: skin like diamond": "/Skin_Like_Diamond",
  "spell: skin like nature": "/Skin_Like_Nature",
  "spell: skin like rock": "/Skin_Like_Rock",
  "spell: skin like steel": "/Skin_Like_Steel",
  "spell: skin like wood": "/Skin_Like_Wood",
  "spell: skin of the shadow": "/Skin_of_the_Shadow",
  "spell: skunkspray": "/Skunkspray",
  "spell: slime mist": "/Slime_Mist",
  "spell: smite": "/Smite",
  "spell: smolder": "/Smolder_(spell)",
  "spell: snare": "/Snare",
  "spell: solon's bewitching bravura": "/Solon%27s_Bewitching_Bravura",
  "spell: solon's bravura": "/Solon%27s_Bravura",
  "spell: solon's charismatic concord": "/Solon%27s_Charismatic_Concord",
  "spell: solon's song of the sirens": "/Solon%27s_Song_of_the_Sirens",
  "spell: song of dawn": "/Song_of_Dawn",
  "spell: song of highsun": "/Song_of_Highsun",
  "spell: song of midnight": "/Song_of_Midnight",
  "spell: song of the deep seas": "/Song_of_the_Deep_Seas",
  "spell: song of twilight": "/Song_of_Twilight",
  "spell: sonic scream": "/Sonic_Scream",
  "spell: soothe": "/Soothe",
  "spell: soul bond": "/Soul_Bond",
  "spell: soul consumption": "/Soul_Consumption",
  "spell: soul devour": "/Soul_Devour",
  "spell: soul leech": "/Soul_Leech",
  "spell: soul well": "/Soul_Well",
  "spell: sound of force": "/Sound_of_Force",
  "spell: spear of warding": "/Spear_of_Warding",
  "spell: specter lifetap": "/Specter_Lifetap",
  "spell: speed of the shissar": "/Speed_of_the_Shissar",
  "spell: sphere of light": "/Sphere_of_Light",
  "spell: spikecoat": "/Spikecoat",
  "spell: spin the bottle": "/Spin_the_Bottle",
  "spell: spirit armor": "/Spirit_Armor",
  "spell: spirit of bear": "/Spirit_of_Bear",
  "spell: spirit of cat": "/Spirit_of_Cat",
  "spell: spirit of cheetah": "/Spirit_of_Cheetah",
  "spell: spirit of monkey": "/Spirit_of_Monkey",
  "spell: spirit of oak": "/Spirit_of_Oak",
  "spell: spirit of ox": "/Spirit_of_Ox",
  "spell: spirit of scale": "/Spirit_of_Scale",
  "spell: spirit of snake": "/Spirit_of_Snake",
  "spell: spirit of the howler": "/Spirit_of_the_Howler",
  "spell: spirit of wolf": "/Spirit_of_Wolf",
  "spell: spirit pouch": "/Spirit_Pouch",
  "spell: spirit quickening": "/Spirit_Quickening",
  "spell: spirit sight": "/Spirit_Sight",
  "spell: spirit strength": "/Spirit_Strength",
  "spell: spirit strike": "/Spirit_Strike",
  "spell: spirit tap": "/Spirit_Tap",
  "spell: splurt": "/Splurt",
  "spell: spook the dead": "/Spook_the_Dead",
  "spell: stability": "/Stability",
  "spell: staff of runes": "/Staff_of_Runes",
  "spell: staff of symbols": "/Staff_of_Symbols",
  "spell: staff of tracing": "/Staff_of_Tracing",
  "spell: staff of warding": "/Staff_of_Warding",
  "spell: stalking probe": "/Stalking_Probe_(Spell)",
  "spell: stalwart regeneration": "/Stalwart_Regeneration",
  "spell: stamina": "/Stamina",
  "spell: starfire": "/Starfire",
  "spell: starshine": "/Starshine",
  "spell: static strike": "/Static_Strike",
  "spell: steal strength": "/Steal_Strength",
  "spell: steam overload": "/Steam_Overload",
  "spell: steelskin": "/Steelskin",
  "spell: stinging swarm": "/Stinging_Swarm",
  "spell: stone breath": "/Stone_Breath",
  "spell: stone spider stun": "/Stone_Spider_Stun",
  "spell: storm strength": "/Storm_Strength",
  "spell: storm strike": "/Storm_Strike",
  "spell: stream of acid": "/Stream_of_Acid",
  "spell: strength": "/Strength",
  "spell: strength of earth": "/Strength_of_Earth",
  "spell: strength of nature": "/Strength_of_Nature",
  "spell: strength of stone": "/Strength_of_Stone",
  "spell: strength of the kunzar": "/Strength_of_the_Kunzar",
  "spell: strengthen": "/Strengthen",
  "spell: strengthen death": "/Strengthen_Death",
  "spell: strike": "/Strike",
  "spell: strike of the chosen": "/Strike_of_the_Chosen",
  "spell: strike of thunder": "/Strike_of_Thunder",
  "spell: strip enchantment": "/Strip_Enchantment",
  "spell: strong disease": "/Strong_Disease",
  "spell: strong poison": "/Strong_Poison",
  "spell: stun": "/Stun",
  "spell: stun breath": "/Stun_Breath",
  "spell: stun command": "/Stun_Command",
  "spell: stunning blow": "/Stunning_Blow",
  "spell: succor": "/Succor",
  "spell: succor: butcher": "/Succor:_Butcher",
  "spell: succor: east": "/Succor:_East",
  "spell: succor: lavastorm": "/Succor:_Lavastorm",
  "spell: succor: north": "/Succor:_North",
  "spell: succor: ro": "/Succor:_Ro",
  "spell: suffocate": "/Suffocate",
  "spell: suffocating sphere": "/Suffocating_Sphere",
  "spell: summon arrows": "/Summon_Arrows",
  "spell: summon bandages": "/Summon_Bandages",
  "spell: summon coldstone": "/Summon_Coldstone",
  "spell: summon companion": "/Summon_Companion",
  "spell: summon corpse": "/Summon_Corpse",
  "spell: summon dagger": "/Summon_Dagger",
  "spell: summon dead": "/Summon_Dead",
  "spell: summon drink": "/Summon_Drink",
  "spell: summon fang": "/Summon_Fang",
  "spell: summon food": "/Summon_Food",
  "spell: summon golin": "/Summon_Golin",
  "spell: summon heatstone": "/Summon_Heatstone",
  "spell: summon holy ale of brell": "/Summon_Holy_Ale_of_Brell",
  "spell: summon lava diamond": "/Summon_Lava_Diamond",
  "spell: summon orb": "/Summon_Orb",
  "spell: summon ring of flight": "/Summon_Ring_of_Flight",
  "spell: summon shard of the core": "/Summon_Shard_of_the_Core",
  "spell: summon throwing dagger": "/Summon_Throwing_Dagger",
  "spell: summon throwing hammer": "/Summon_Throwing_Hammer",
  "spell: summon waterstone": "/Summon_Waterstone",
  "spell: summon wisp": "/Summon_Wisp",
  "spell: summoning: air": "/Summoning:_Air",
  "spell: summoning: earth": "/Summoning:_Earth",
  "spell: summoning: fire": "/Summoning:_Fire",
  "spell: summoning: water": "/Summoning:_Water",
  "spell: sunbeam": "/Sunbeam",
  "spell: sunskin": "/Sunskin",
  "spell: sunstrike": "/Sunstrike",
  "spell: superior camouflage": "/Superior_Camouflage",
  "spell: superior healing": "/Superior_Healing",
  "spell: supernova": "/Supernova",
  "spell: surge of enfeeblement": "/Surge_of_Enfeeblement",
  "spell: swamp port": "/Swamp_Port",
  "spell: swarm of retribution": "/Swarm_of_Retribution",
  "spell: swarming pain": "/Swarming_Pain",
  "spell: swift like the wind": "/Swift_Like_The_Wind",
  "spell: swift spirit": "/Swift_Spirit",
  "spell: sword of runes": "/Sword_of_Runes",
  "spell: symbol of marzin": "/Symbol_of_Marzin",
  "spell: symbol of naltron": "/Symbol_of_Naltron",
  "spell: symbol of pinzarn": "/Symbol_of_Pinzarn",
  "spell: symbol of ryltan": "/Symbol_of_Ryltan",
  "spell: symbol of transal": "/Symbol_of_Transal",
  "spell: sympathetic aura": "/Sympathetic_Aura",
  "spell: symphonic harmony": "/Symphonic_Harmony",
  "spell: system shock i": "/System_Shock_I",
  "spell: system shock ii": "/System_Shock_II",
  "spell: system shock iii": "/System_Shock_III",
  "spell: system shock iv": "/System_Shock_IV",
  "spell: system shock v": "/System_Shock_V",
  "spell: syvelian's anti-magic aria": "/Syvelian%27s_Anti-Magic_Aria",
  "spell: tagar's insects": "/Tagar%27s_Insects",
  "spell: tainted breath": "/Tainted_Breath",
  "spell: talisman of altuna": "/Talisman_of_Altuna",
  "spell: talisman of jasinth": "/Talisman_of_Jasinth",
  "spell: talisman of kragg": "/Talisman_of_Kragg",
  "spell: talisman of shadoo": "/Talisman_of_Shadoo",
  "spell: talisman of the brute": "/Talisman_of_the_Brute",
  "spell: talisman of the cat": "/Talisman_of_the_Cat",
  "spell: talisman of the raptor": "/Talisman_of_the_Raptor",
  "spell: talisman of the rhino": "/Talisman_of_the_Rhino",
  "spell: talisman of the serpent": "/Talisman_of_the_Serpent",
  "spell: talisman of tnarg": "/Talisman_of_Tnarg",
  "spell: taper enchantment": "/Taper_Enchantment",
  "spell: tarew's aquatic ayre": "/Tarew%27s_Aquatic_Ayre",
  "spell: tashan": "/Tashan",
  "spell: tashani": "/Tashani",
  "spell: tashania": "/Tashania",
  "spell: tashanian": "/Tashanian",
  "spell: tears of druzzil": "/Tears_of_Druzzil",
  "spell: tears of solusek": "/Tears_of_Solusek",
  "spell: telescope": "/Telescope",
  "spell: tepid deeds": "/Tepid_Deeds",
  "spell: terrorize animal": "/Terrorize_Animal",
  "spell: the dain's justice": "/The_Dain%27s_Justice",
  "spell: the unspoken word": "/The_Unspoken_Word",
  "spell: theft of thought": "/Theft_of_Thought",
  "spell: thicken mana": "/Thicken_Mana",
  "spell: thistlecoat": "/Thistlecoat",
  "spell: thorncoat": "/Thorncoat",
  "spell: thorny shield": "/Thorny_Shield",
  "spell: thrall of bones": "/Thrall_of_Bones",
  "spell: thunder blast": "/Thunder_Blast",
  "spell: thunder strike": "/Thunder_Strike",
  "spell: thunderbold": "/Thunderbold",
  "spell: thunderclap": "/Thunderclap",
  "spell: thurgadin gate": "/Thurgadin_Gate",
  "spell: tigir's insects": "/Tigir%27s_Insects",
  "spell: tishan's clash": "/Tishan%27s_Clash",
  "spell: tishan's relocation": "/Tishan%27s_Relocation",
  "spell: tishan`s discord": "/Tishan%60s_Discord",
  "spell: togor's insects": "/Togor%27s_Insects",
  "spell: torbas' acid blast": "/Torbas%27_Acid_Blast",
  "spell: torment": "/Torment",
  "spell: torment of argli": "/Torment_of_Argli",
  "spell: torment of shadows": "/Torment_of_Shadows",
  "spell: torpor": "/Torpor",
  "spell: torrent of poison": "/Torrent_of_Poison",
  "spell: touch of night": "/Touch_of_Night",
  "spell: tox gate": "/Tox_Gate",
  "spell: tox portal": "/Tox_Portal",
  "spell: track corpse": "/Track_Corpse",
  "spell: trakanon tail": "/Trakanon_Tail",
  "spell: trakanon's touch": "/Trakanon%27s_Touch",
  "spell: translocate": "/Translocate",
  "spell: translocate: cazic": "/Translocate:_Cazic",
  "spell: translocate: cobalt scar": "/Translocate:_Cobalt_Scar",
  "spell: translocate: combine": "/Translocate:_Combine",
  "spell: translocate: common": "/Translocate:_Common",
  "spell: translocate: fay": "/Translocate:_Fay",
  "spell: translocate: great divide": "/Translocate:_Great_Divide",
  "spell: translocate: group": "/Translocate:_Group",
  "spell: translocate: iceclad": "/Translocate:_Iceclad",
  "spell: translocate: nek": "/Translocate:_Nek",
  "spell: translocate: north": "/Translocate:_North",
  "spell: translocate: ro": "/Translocate:_Ro",
  "spell: translocate: tox": "/Translocate:_Tox",
  "spell: translocate: wakening lands": "/Translocate:_Wakening_Lands",
  "spell: translocate: west": "/Translocate:_West",
  "spell: travelerboots": "/TravelerBoots",
  "spell: treeform": "/Treeform",
  "spell: tremor": "/Tremor",
  "spell: trepidation": "/Trepidation",
  "spell: trucidation": "/Trucidation",
  "spell: true north": "/True_North",
  "spell: truesight": "/Truesight",
  "spell: tsunami": "/Tsunami",
  "spell: tumultuous strength": "/Tumultuous_Strength",
  "spell: tunare's request": "/Tunare%27s_Request",
  "spell: turgur's insects": "/Turgur%27s_Insects",
  "spell: turgur`s insects": "/Turgur%60s_Insects",
  "spell: turning of the unnatural": "/Turning_of_the_Unnatural",
  "spell: turtle skin": "/Turtle_Skin",
  "spell: tuyen's chant of flame": "/Tuyen%27s_Chant_of_Flame",
  "spell: tuyen's chant of frost": "/Tuyen%27s_Chant_of_Frost",
  "spell: uleen's animation": "/Uleen%27s_Animation",
  "spell: ultravision": "/Ultravision",
  "spell: umbra": "/Umbra",
  "spell: unfailing reverence": "/Unfailing_Reverence",
  "spell: unswerving hammer": "/Unswerving_Hammer",
  "spell: upheaval": "/Upheaval",
  "spell: valiant companion": "/Valiant_Companion",
  "spell: valor": "/Valor",
  "spell: vampire charm": "/Vampire_Charm",
  "spell: vampiric curse": "/Vampiric_Curse",
  "spell: vampiric embrace": "/Vampiric_Embrace",
  "spell: velium shards": "/Velium_Shards",
  "spell: velocity": "/Velocity",
  "spell: vengeance of al'kabor": "/Vengeance_of_Al%27Kabor",
  "spell: vengeance of the glades": "/Vengeance_of_the_Glades",
  "spell: venom of the snake": "/Venom_of_the_Snake",
  "spell: verlekarnorm's disaster": "/Verlekarnorm%27s_Disaster",
  "spell: verses of victory": "/Verses_of_Victory",
  "spell: vexing mordinia": "/Vexing_Mordinia",
  "spell: vigilant spirit": "/Vigilant_Spirit",
  "spell: vigor": "/Vigor",
  "spell: vilia's chorus of celerity": "/Vilia%27s_Chorus_of_Celerity",
  "spell: vilia's verses of celerity": "/Vilia%27s_Verses_of_Celerity",
  "spell: vision": "/Vision",
  "spell: visions of grandeur": "/Visions_of_Grandeur",
  "spell: vocarate: air": "/Vocarate:_Air",
  "spell: vocarate: earth": "/Vocarate:_Earth",
  "spell: vocarate: fire": "/Vocarate:_Fire",
  "spell: vocarate: water": "/Vocarate:_Water",
  "spell: voice graft": "/Voice_Graft",
  "spell: voice of the berserker": "/Voice_of_the_Berserker",
  "spell: voltaic draught": "/Voltaic_Draught",
  "spell: wake of karana": "/Wake_of_Karana",
  "spell: wake of tranquility": "/Wake_of_Tranquility",
  "spell: wakening lands gate": "/Wakening_Lands_Gate",
  "spell: wakening lands portal": "/Wakening_Lands_Portal",
  "spell: walking sleep": "/Walking_Sleep",
  "spell: wandering mind": "/Wandering_Mind",
  "spell: ward summoned": "/Ward_Summoned",
  "spell: ward undead": "/Ward_Undead",
  "spell: wave of cold": "/Wave_of_Cold",
  "spell: wave of enfeeblement": "/Wave_of_Enfeeblement",
  "spell: wave of fear": "/Wave_of_Fear",
  "spell: wave of fire": "/Wave_of_Fire",
  "spell: wave of flame": "/Wave_of_Flame",
  "spell: wave of healing": "/Wave_of_Healing",
  "spell: wave of heat": "/Wave_of_Heat",
  "spell: waves of the deep sea": "/Waves_of_the_Deep_Sea",
  "spell: weak poison": "/Weak_Poison",
  "spell: weaken": "/Weaken",
  "spell: weakening poison i": "/Weakening_Poison_I",
  "spell: weakening poison ii": "/Weakening_Poison_II",
  "spell: weakening poison iii": "/Weakening_Poison_III",
  "spell: weakening poison iv": "/Weakening_Poison_IV",
  "spell: weakness": "/Weakness",
  "spell: west gate": "/West_Gate",
  "spell: west portal": "/West_Portal",
  "spell: whirl till you hurl": "/Whirl_Till_You_Hurl",
  "spell: whirlbolt": "/Whirlbolt",
  "spell: whirling wind": "/Whirling_Wind",
  "spell: whirlwind": "/Whirlwind",
  "spell: wildfire": "/Wildfire",
  "spell: wind of the north": "/Wind_of_the_North",
  "spell: wind of the south": "/Wind_of_the_South",
  "spell: wind of tishani": "/Wind_of_Tishani",
  "spell: wind of tishanian": "/Wind_of_Tishanian",
  "spell: winds of gelid": "/Winds_of_Gelid",
  "spell: winged death": "/Winged_Death",
  "spell: winter's roar": "/Winter%27s_Roar",
  "spell: wolf form": "/Wolf_Form",
  "spell: wonderous rapidity": "/Wonderous_Rapidity",
  "spell: word divine": "/Word_Divine",
  "spell: word of healing": "/Word_of_Healing",
  "spell: word of health": "/Word_of_Health",
  "spell: word of pain": "/Word_of_Pain",
  "spell: word of redemption": "/Word_of_Redemption",
  "spell: word of restoration": "/Word_of_Restoration",
  "spell: word of shadow": "/Word_of_Shadow",
  "spell: word of souls": "/Word_of_Souls",
  "spell: word of spirit": "/Word_of_Spirit",
  "spell: word of vigor": "/Word_of_Vigor",
  "spell: wrath": "/Wrath",
  "spell: wrath of al'kabor": "/Wrath_of_Al%27Kabor",
  "spell: wrath of nature": "/Wrath_of_Nature",
  "spell: wrath of the elements": "/Wrath_of_the_Elements",
  "spell: yaulp": "/Yaulp",
  "spell: yaulp ii": "/Yaulp_II",
  "spell: yaulp iii": "/Yaulp_III",
  "spell: yaulp iv": "/Yaulp_IV",
  "spell: yegoreff's animation": "/Yegoreff%27s_Animation",
  "spell: ykesha": "/Ykesha",
  "spell: yonder": "/Yonder",
  "spell: zumaik`s animation": "/Zumaik%60s_Animation",
};

export const spellsMapById = mapFromData(spellsData);
