interface RaidEvent {
  name: string;
  value: number;
  id: number;
}

const events: RaidEvent[] = [
  { name: "[Green] 7-day targets", value: 1, id: 18 },
  { name: "[Green] Kelorek'Dar", value: 1, id: 81 },
  { name: "[Green] Black Reavers", value: 1, id: 16 },
  { name: "[Green] Book of Souls Race", value: 1, id: 33 },
  { name: "[Green] Bot Power Leveling", value: 0, id: 127 },
  { name: "[Green] Castle Crusade", value: 1, id: 31 },
  { name: "[Green] CastleQuest", value: 0, id: 32 },
  { name: "[Green] Cazic Thule", value: 3, id: 64 },
  { name: "[Green] Chardok Royals", value: 1, id: 28 },
  { name: "[Green] Dain Frostweaver IV", value: 1, id: 133 },
  { name: "[Green] Derakor the Vindicator", value: 1, id: 77 },
  { name: "[Green] Discord DKP auctions", value: 0, id: 19 },
  { name: "[Green] Dracholiche", value: 3, id: 68 },
  { name: "[Green] Earthquake", value: 1, id: 131 },
  { name: "[Green] Emperor Chottal", value: 1, id: 23 },
  { name: "[Green] Faydedar", value: 1, id: 27 },
  { name: "[Green] Fear Golem", value: 1, id: 30 },
  { name: "[Green] Fear Golem (earthquake)", value: 2, id: 72 },
  { name: "[Green] Fire Giants", value: 1, id: 2 },
  { name: "[Green] Fungi King", value: 1, id: 29 },
  { name: "[Green] Garzicor", value: 1, id: 92 },
  { name: "[Green] Gorenaire", value: 3, id: 66 },
  { name: "[Green] Gozzrem", value: 1, id: 105 },
  { name: "[Green] Gozzrem (earthquake)", value: 2, id: 104 },
  { name: "[Green] Guardian Wurms", value: 1, id: 22 },
  { name: "[Green] Halls of Testing", value: 1, id: 38 },
  { name: "[Green] Ikatiar", value: 1, id: 100 },
  { name: "[Green] Ikatiar (earthquake)", value: 2, id: 73 },
  { name: "[Green] Ixiblat Fer", value: 1, id: 91 },
  { name: "[Green] KP Conversion", value: 0, id: 25 },
  { name: "[Green] Kael", value: 1, id: 36 },
  { name: "[Green] King Tranix", value: 1, id: 12 },
  { name: "[Green] Lady Vox", value: 3, id: 99 },
  { name: "[Green] Lord Nagafen", value: 1, id: 125 },
  { name: "[Green] Lord Yelinak", value: 3, id: 109 },
  { name: "[Green] Magi P'Tasa", value: 1, id: 101 },
  { name: "[Green] Magi P'Tasa (earthquake)", value: 2, id: 86 },
  { name: "[Green] Misc", value: 1, id: 20 },
  { name: "[Green] Muster in Dreadlands", value: 1, id: 57 },
  { name: "[Green] Muster in Kithicor", value: 1, id: 43 },
  { name: "[Green] Muster in South Ro", value: 1, id: 42 },
  { name: "[Green] Muster in Wakening Lands", value: 1, id: 44 },
  { name: "[Green] PP4DKP", value: 1, id: 132 },
  { name: "[Green] Phinny", value: 1, id: 3 },
  { name: "[Green] Plane of Fear", value: 1, id: 11 },
  { name: "[Green] Plane of Growth", value: 1, id: 41 },
  { name: "[Green] Plane of Hate", value: 1, id: 15 },
  { name: "[Green] Plane of Sky", value: 1, id: 17 },
  { name: "[Green] Ragefire", value: 1, id: 90 },
  { name: "[Green] Ring War", value: 1, id: 134 },
  { name: "[Green] Scheduled Raid", value: 1, id: 112 },
  { name: "[Green] Sebilis Juggernauts", value: 1, id: 24 },
  { name: "[Green] Sebilis Keying", value: 1, id: 9 },
  { name: "[Green] Severilous", value: 3, id: 94 },
  { name: "[Green] Sir Lucan", value: 1, id: 5 },
  { name: "[Green] Six Necks", value: 1, id: 93 },
  { name: "[Green] Skyfire Spell Farm", value: 1, id: 8 },
  { name: "[Green] Special Event", value: 1, id: 26 },
  { name: "[Green] Talendor", value: 1, id: 80 },
  { name: "[Green] Telkorenar", value: 1, id: 106 },
  { name: "[Green] Telkorenar (earthquake)", value: 2, id: 74 },
  { name: "[Green] Trakanon", value: 3, id: 45 },
  { name: "[Green] Vaniki", value: 1, id: 82 },
  { name: "[Green] Velketor", value: 1, id: 102 },
  { name: "[Green] Velketor (earthquake)", value: 2, id: 69 },
  { name: "[Green] Venril Sathir", value: 3, id: 65 },
  { name: "[Green] Venril Sathir's Remains", value: 1, id: 95 },
  { name: "[Green] Western Wastes", value: 1, id: 37 },
  { name: "[Green] Wuoshi", value: 1, id: 103 },
  { name: "[Green] Wuoshi (earthquake)", value: 2, id: 75 },
  { name: "[Green] nToV", value: 1, id: 123 },
  { name: "[Green] wToV", value: 1, id: 124 },
];

export const raidEventsMap = events.reduce((m, e) => {
  m[e.name?.replace("[Green] ", "")] = e;
  return m;
}, {} as { [label: string]: RaidEvent });
