interface RaidEvent {
  name: string;
  value: number;
}

const events: RaidEvent[] = [
  { name: "[Green] 7-day targets", value: 1 },
  { name: "[Green] Kelorek'Dar", value: 1 },
  { name: "[Green] Black Reavers", value: 1 },
  { name: "[Green] Book of Souls Race", value: 1 },
  { name: "[Green] Bot Power Leveling", value: 0 },
  { name: "[Green] Castle Crusade", value: 1 },
  { name: "[Green] CastleQuest", value: 0 },
  { name: "[Green] Cazic Thule", value: 3 },
  { name: "[Green] Chardok Royals", value: 1 },
  { name: "[Green] Dain Frostweaver IV", value: 1 },
  { name: "[Green] Derakor the Vindicator", value: 1 },
  { name: "[Green] Discord DKP auctions", value: 0 },
  { name: "[Green] Dracholiche", value: 3 },
  { name: "[Green] Earthquake", value: 1 },
  { name: "[Green] Emperor Chottal", value: 1 },
  { name: "[Green] Faydedar", value: 1 },
  { name: "[Green] Fear Golem", value: 1 },
  { name: "[Green] Fear Golem (earthquake)", value: 2 },
  { name: "[Green] Fire Giants", value: 1 },
  { name: "[Green] Fungi King", value: 1 },
  { name: "[Green] Garzicor", value: 1 },
  { name: "[Green] Gorenaire", value: 3 },
  { name: "[Green] Gozzrem", value: 1 },
  { name: "[Green] Gozzrem (earthquake)", value: 2 },
  { name: "[Green] Guardian Wurms", value: 1 },
  { name: "[Green] Halls of Testing", value: 1 },
  { name: "[Green] Ikatiar", value: 1 },
  { name: "[Green] Ikatiar (earthquake)", value: 2 },
  { name: "[Green] Ixiblat Fer", value: 1 },
  { name: "[Green] KP Conversion", value: 0 },
  { name: "[Green] Kael", value: 1 },
  { name: "[Green] King Tranix", value: 1 },
  { name: "[Green] Lady Vox", value: 3 },
  { name: "[Green] Lord Nagafen", value: 1 },
  { name: "[Green] Lord Yelinak", value: 3 },
  { name: "[Green] Magi P'Tasa", value: 1 },
  { name: "[Green] Magi P'Tasa (earthquake)", value: 2 },
  { name: "[Green] Misc", value: 1 },
  { name: "[Green] Muster in Dreadlands", value: 1 },
  { name: "[Green] Muster in Kithicor", value: 1 },
  { name: "[Green] Muster in South Ro", value: 1 },
  { name: "[Green] Muster in Wakening Lands", value: 1 },
  { name: "[Green] PP4DKP", value: 1 },
  { name: "[Green] Phinny", value: 1 },
  { name: "[Green] Plane of Fear", value: 1 },
  { name: "[Green] Plane of Growth", value: 1 },
  { name: "[Green] Plane of Hate", value: 1 },
  { name: "[Green] Plane of Sky", value: 1 },
  { name: "[Green] Ragefire", value: 1 },
  { name: "[Green] Ring War", value: 1 },
  { name: "[Green] Scheduled Raid", value: 1 },
  { name: "[Green] Sebilis Juggernauts", value: 1 },
  { name: "[Green] Sebilis Keying", value: 1 },
  { name: "[Green] Severilous", value: 3 },
  { name: "[Green] Sir Lucan", value: 1 },
  { name: "[Green] Six Necks", value: 1 },
  { name: "[Green] Skyfire Spell Farm", value: 1 },
  { name: "[Green] Special Event", value: 1 },
  { name: "[Green] Talendor", value: 1 },
  { name: "[Green] Telkorenar", value: 1 },
  { name: "[Green] Telkorenar (earthquake)", value: 2 },
  { name: "[Green] Trakanon", value: 3 },
  { name: "[Green] Vaniki", value: 1 },
  { name: "[Green] Velketor", value: 1 },
  { name: "[Green] Velketor (earthquake)", value: 2 },
  { name: "[Green] Venril Sathir", value: 3 },
  { name: "[Green] Venril Sathir's Remains", value: 1 },
  { name: "[Green] Western Wastes", value: 1 },
  { name: "[Green] Wuoshi", value: 1 },
  { name: "[Green] Wuoshi (earthquake)", value: 2 },
  { name: "[Green] nToV", value: 1 },
  { name: "[Green] wToV", value: 1 },
];

export const raidEventsMap = events.reduce((m, e) => {
  m[e.name?.replace("[Green] ", "")] = e;
  return m;
}, {} as { [label: string]: RaidEvent });
